# Generated by Django 4.0.5 on 2022-06-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deserialize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='year',
            field=models.IntegerField(),
        ),
    ]
