# Generated by Django 4.0.5 on 2022-06-12 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deserialize', '0002_alter_detail_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='deserialize.country'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='petroleum_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petroleum_product', to='deserialize.petroleumproduct'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
