# Generated by Django 4.0.5 on 2022-06-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deserialize', '0003_alter_detail_country_alter_detail_petroleum_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='year',
            field=models.DateField(),
        ),
    ]
